apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-config
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  DEBUG: {{ .Values.config.debug | quote }}
  PORT: {{ .Values.config.backendPort | quote }}
  LLM_PROVIDER: {{ .Values.config.llmProvider | quote }}
  GROQ_MODEL: {{ .Values.config.groqModel | quote }}
  NEXT_PUBLIC_API_URL: "http://{{ include "todo-chatbot.fullname" . }}-backend:{{ .Values.backend.service.port }}/api/v1"
