apiVersion: v2
name: todo-chatbot
description: Cloud-Native Todo AI Chatbot â€” Local Kubernetes Deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - todo
  - chatbot
  - fastapi
  - nextjs
  - mcp
maintainers:
  - name: DC
