apiVersion: v2
name: todo-chatbot
description: Cloud-Native Event-Driven Todo AI Chatbot â€” Kubernetes Deployment with Kafka + Dapr
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - todo
  - chatbot
  - fastapi
  - nextjs
  - mcp
  - kafka
  - dapr
  - event-driven
  - cloud-native
maintainers:
  - name: DC
